spring:
#  security:
#    user:
#      name: admin
#      password: 123456
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/security-demo/security-db;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9093;DB_CLOSE_DELAY=-1

logging:
  level:
    root: debug
